// <auto-generated />
namespace CarDealership.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_IsAccountEnabled : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_IsAccountEnabled));
        
        string IMigrationMetadata.Id
        {
            get { return "201708022255368_added_IsAccountEnabled"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
